# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EhcJCBcknrl3sbJknTuP0gwNNMMoMiLn
"""

#Fatimah Mousa Al Mousa
#Ruqayah Mousa Al Mousa
#Sarah Hamdan Alqurashi
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns
from matplotlib.colors import ListedColormap

data_set = pd.read_csv('/content/output.csv')


x = data_set.iloc[:, [2, 3,4,5]].values
y = data_set.iloc[:, 6].values


x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=0)


st_x = StandardScaler()
x_train = st_x.fit_transform(x_train)
x_test = st_x.transform(x_test)


classifier = KNeighborsClassifier(n_neighbors=5, metric='minkowski', p=2)
classifier.fit(x_train, y_train)


y_pred = classifier.predict(x_test)


cm = confusion_matrix(y_test, y_pred)


accuracy = (cm[0, 0] + cm[1, 1]) / np.sum(cm)


print("Confusion Matrix:")
print(cm)
print("Accuracy:", accuracy)


plt.figure(figsize=(6, 4))
sns.heatmap(cm, annot=True, fmt='d', cmap='Greens', cbar=False)
plt.title('Confusion Matrix')
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.show()


plt.figure(figsize=(6, 4))
plt.bar(['Accuracy'], [accuracy], color='green')
plt.ylim(0, 1)
plt.title('Model Accuracy')
plt.show()